### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xingluo233** [VeronicaAlexia/BoluobaoAPI#1]
大佬，我不会golang，你能说下请求头里sfsecurity里的nonce和sign的生成算法吗😂

**Comment by VeronicaAlexia** [comment]
https://github.com/VeronicaAlexia/BoluobaoAPI/blob/1901482f3c90cad042277cfcbbee97dbb9c492a9/request/headers.go#L13

**Comment by VeronicaAlexia** [comment]
> 大佬，我不会golang，你能说下请求头里sfsecurity里的nonce和sign的生成算法吗😂
目前android sfsecurity算法并没有在本项目里开源,只开源了WeChat Authorization生成的算法
具体原因参考:https://github.com/VeronicaAlexia/pineapple-backups/issues/3#issuecomment-1253298063

**Comment by xingluo233** [comment]
> > 大佬，我不会golang，你能说下请求头里sfsecurity里的nonce和sign的生成算法吗😂
> 目前android sfsecurity算法并没有在本项目里开源,只开源了WeChat Authorization生成的算法
> 具体原因参考:https://github.com/VeronicaAlexia/pineapple-backups/issues/3#issuecomment-1253298063
> 
> 

好的👌

**Comment by VeronicaAlexia** [comment]
https://github.com/deepink-app/booksource这个应该是你的项目吧
[linovelib](https://github.com/xingluo233/booksource-1/blob/beta/sources/linovelib.com.js)近期对文字做了混淆处理,我已经通过js逆向出来了混淆部分的代码:https://github.com/VeronicaAlexia/linovel/blob/main/src/decodes.py

**Comment by xingluo233** [comment]
> https://github.com/deepink-app/booksource这个应该是你的项目吧
> [linovelib](https://github.com/xingluo233/booksource-1/blob/beta/sources/linovelib.com.js)近期对文字做了混淆处理,我已经通过js逆向出来了混淆部分的代码:https://github.com/VeronicaAlexia/linovel/blob/main/src/decodes.py

好的，感谢提醒，不过有例子吗，我看了好几本书都没发现这个问题

**Comment by VeronicaAlexia** [comment]
> > [https://github.com/deepink-app/booksource 这个应该是你的项目吧](https://github.com/deepink-app/booksource%E8%BF%99%E4%B8%AA%E5%BA%94%E8%AF%A5%E6%98%AF%E4%BD%A0%E7%9A%84%E9%A1%B9%E7%9B%AE%E5%90%A7) [linovelib](https://github.com/xingluo233/booksource-1/blob/beta/sources/linovelib.com.js)近期对文字做了混淆处理，我已经通过js逆向出来了混淆部分的代码：https://github.com/VeronicaAlexia/linovel/blob/main/src/decodes.py
> 
> 好的，感谢提醒，不过有例子吗，我看了好几本书都没发现这个问题

刚刚才发现,linovelib并没有对https://w.linovelib.com下的的章节做混淆处理,只对https://www.linovelib.com/章节做了混淆

**Comment by xingluo233** [comment]
> 我最近也在使用厚墨阅读器阅读小说,我对厚墨书源的制作挺感兴趣,如果可以的话是否能与你使用Telegram或者Discord进行交流呢?

https://t.me/xingluo233
