### ISSUE TITLE
接口校检失败

### ISSUE THREAD

**Issue by Anvei** [VeronicaAlexia/BoluobaoAPI#2]
README示例运行结果："Content Error: 接口校验失败,请尽快把APP升级到最新版哦~"。
另外我想求教一下，大佬是如何获取章节具体内容的，我根据抓包工具得到的请求信息构建的http请求总是返回417错误码，获取不到具体内容，只获取到了章节信息

**Comment by VeronicaAlexia** [comment]
你可以使用config.AppConfig.App = flase切换接口实现章节访问
